// Generated by GitHub Copilot
using LeaveManagement.Domain.Contracts.Services;

namespace LeaveManagement.Infrastructure.Services;

/// <summary>
/// Wraps the system clock to allow time-dependent logic to be tested without coupling to DateTime.Now.
/// </summary>
public class SystemTimeProvider : ITimeProvider
{
    /// <inheritdoc />
    public DateTime Today => DateTime.Today;

    /// <inheritdoc />
    public DateTime UtcNow => DateTime.UtcNow;
}
